version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: test1
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "./wait-for-it.sh db:5432 -- python manage.py migrate && pytest && if [ $? -eq 0 ]; then python manage.py runserver 0.0.0.0:8000; else echo 'Migrations or tests failed.' && exit 1; fi"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
