# Generated by Django 5.1.1 on 2024-10-01 12:28

from django.db import migrations

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Breed = apps.get_model('kittens', 'Breed')
    Kitten = apps.get_model('kittens', 'Kitten')
    User = apps.get_model('auth', 'User')

    # Создание нескольких пород
    siamese = Breed.objects.create(name='Siamese')
    persian = Breed.objects.create(name='Persian')
    sphynx = Breed.objects.create(name='Sphynx')

    # Создание пользователя, который будет владельцем котят
    owner = User.objects.create(username="user", password="password")

    # Создание котят
    Kitten.objects.create(breed=siamese, color='White', age_in_months=5, description='Very playful and active', owner=owner)
    Kitten.objects.create(breed=persian, color='Black', age_in_months=7, description='Calm and quiet', owner=owner)
    Kitten.objects.create(breed=sphynx, color='Pink', age_in_months=3, description='Friendly and curious', owner=owner)

class Migration(migrations.Migration):

    dependencies = [
        ('kittens', '0001_initial'),  # Замените на номер вашей миграции
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]

